from __future__ import annotations

import numpy as np


def perturb_training_spectra(
    X: np.ndarray,
    y: np.ndarray,
    *,
    n_aug: int = 1,
    seed: int = 2025,
    noise_scale: float = 0.01,
    baseline_scale: float = 0.01,
    shift_max: int = 2,
) -> tuple[np.ndarray, np.ndarray]:
    """Generate perturbed training spectra after preprocessing.

    The manuscript states that augmented samples were generated by applying
    perturbations to the preprocessed training spectra. This helper implements
    conservative spectral perturbations: small additive noise, low-order
    baseline drift, and small spectral shifts.
    """

    X = np.asarray(X, dtype=np.float32)
    y = np.asarray(y, dtype=np.float32).reshape(-1)
    if int(n_aug) <= 0:
        return X.copy(), y.copy()
    rng = np.random.default_rng(int(seed))
    all_X = [X]
    all_y = [y]
    n, p = X.shape
    coord = np.linspace(-1.0, 1.0, p, dtype=np.float32)
    signal_span = np.maximum(np.ptp(X, axis=1, keepdims=True), 1e-6)
    for _ in range(int(n_aug)):
        Xa = X.copy()
        Xa += rng.normal(0.0, float(noise_scale), size=X.shape).astype(np.float32) * signal_span
        coeff0 = rng.normal(0.0, float(baseline_scale), size=(n, 1)).astype(np.float32) * signal_span
        coeff1 = rng.normal(0.0, float(baseline_scale), size=(n, 1)).astype(np.float32) * signal_span
        Xa += coeff0 + coeff1 * coord.reshape(1, -1)
        if int(shift_max) > 0:
            shifts = rng.integers(-int(shift_max), int(shift_max) + 1, size=n)
            for i, shift in enumerate(shifts):
                if shift:
                    Xa[i] = np.roll(Xa[i], int(shift))
        all_X.append(Xa.astype(np.float32, copy=False))
        all_y.append(y.copy())
    return np.concatenate(all_X, axis=0), np.concatenate(all_y, axis=0)

