targets:
  cellulose:
    plsr:
      preprocessing: MSC
      latent_variables: 14
    svr:
      preprocessing: SNV
      kernel: linear
      C: 15.8407
      epsilon: 0.7806
      gamma: scale
    xgboost:
      preprocessing: SNV + sgdiff(w=21,d=1)
      n_estimators: 565
      max_depth: 2
      learning_rate: 0.0193
      subsample: 0.83
      colsample: 0.8641
      min_child_weight: 10
      alpha: 7.86e-05
      lambda: 0.0019
      gamma: 0.8914
    cnn:
      preprocessing: sgdiff(w=33,d=1)
      filters: [32, 32, 16]
      kernels: [17, 17, 5]
      strides: [1, 2]
      se_mode: [SE3]
      se_attention_after_conv:
        SE1: false
        SE2: false
        SE3: true
      dense_units: 64
      dropout: 0.35
      batch_size: 128
      learning_rate: 6.08e-05
      weight_decay: 3.08e-06
    srem_cnn:
      preprocessing: sgdiff(w=9,d=1)
      se_mode: [SE2, SE3]
      se_attention_after_conv:
        SE1: false
        SE2: true
        SE3: true
      se_reduction: 2
      dropout: 0.05
      dense_units: 256
      block_1_filters: [16, 8, 32]
      block_1_kernels: [23, 3, 11]
      block_2_filters: [8, 8, 32]
      block_2_kernels: [13, 23, 13]
      block_3_filters: [16, 32, 4]
      block_3_kernels: [5, 23, 21]
      stride_1: 1
      stride_2: 2
      batch_size: 256
      learning_rate: 2.85e-05
      weight_decay: 0.0073
  hemicellulose:
    plsr:
      preprocessing: MSC
      latent_variables: 15
    svr:
      preprocessing: MSC
      kernel: linear
      C: 16.7775
      epsilon: 0.6284
      gamma: scale
    xgboost:
      preprocessing: sgdiff(w=27,d=2)
      n_estimators: 1014
      max_depth: 5
      learning_rate: 0.022
      subsample: 0.8639
      colsample: 0.9405
      min_child_weight: 10
      alpha: 0.04
      lambda: 0.0012
      gamma: 4.5107
    cnn:
      preprocessing: sgdiff(w=5,d=1)
      filters: [64, 128, 32]
      kernels: [7, 19, 13]
      strides: [2, 2]
      se_mode: [SE3]
      se_attention_after_conv:
        SE1: false
        SE2: false
        SE3: true
      dense_units: 128
      dropout: 0.3
      batch_size: 128
      learning_rate: 1.18e-04
      weight_decay: 1.54e-05
    srem_cnn:
      preprocessing: sgdiff(w=5,d=1)
      se_mode: [SE2, SE3]
      se_attention_after_conv:
        SE1: false
        SE2: true
        SE3: true
      se_reduction: 16
      dropout: 0.1
      dense_units: 128
      block_1_filters: [128, 128, 8]
      block_1_kernels: [5, 9, 5]
      block_2_filters: [16, 64, 128]
      block_2_kernels: [27, 21, 27]
      block_3_filters: [8, 8, 128]
      block_3_kernels: [19, 17, 21]
      stride_1: 1
      stride_2: 2
      batch_size: 512
      learning_rate: 1.67e-06
      weight_decay: 0
  lignin:
    plsr:
      preprocessing: MSC
      latent_variables: 20
    svr:
      preprocessing: SNV + sgdiff(w=21,d=1)
      kernel: linear
      C: 0.4861
      epsilon: 0.1346
      gamma: scale
    xgboost:
      preprocessing: SNV
      n_estimators: 1048
      max_depth: 2
      learning_rate: 0.0142
      subsample: 0.7876
      colsample: 0.9043
      min_child_weight: 2
      alpha: 6.91e-08
      lambda: 5.2037
      gamma: 2.776
    cnn:
      preprocessing: SNV + sgdiff(w=19,d=1)
      filters: [64, 32, 32]
      kernels: [7, 25, 17]
      strides: [2, 2]
      se_mode: [SE3]
      se_attention_after_conv:
        SE1: false
        SE2: false
        SE3: true
      dense_units: 256
      dropout: 0.4
      batch_size: 128
      learning_rate: 2.23e-04
      weight_decay: 4.89e-06
    srem_cnn:
      preprocessing: SNV + sgdiff(w=7,d=1)
      se_mode: [SE3]
      se_attention_after_conv:
        SE1: false
        SE2: false
        SE3: true
      se_reduction: 8
      dropout: 0.45
      dense_units: 64
      block_1_filters: [128, 4, 32]
      block_1_kernels: [25, 11, 19]
      block_2_filters: [128, 8, 64]
      block_2_kernels: [3, 23, 7]
      block_3_filters: [32, 4, 8]
      block_3_kernels: [13, 23, 17]
      stride_1: 2
      stride_2: 1
      batch_size: 128
      learning_rate: 5.42e-06
      weight_decay: 1.82e-05
